# Copiar este archivo en nginx.conf en c:\nginx\conf\nginx.conf
# tenemos 4 workers y despues abrir 4 terminales que ejecuten puerto 5001 , 5002,5003,5004 por ejemplo con:
# $env:PORT=5001
# python direct-communication/rest_server.py  (situado en la carpeta del trabajo)

worker_processes  1;

events {
    worker_connections  1024;
}

http {
    upstream ticket_workers {
        server 127.0.0.1:5001;
        server 127.0.0.1:5002;
        server 127.0.0.1:5003;
        server 127.0.0.1:5004;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://ticket_workers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}